package com.scp.java.endtoend;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "BOOK_INFO")
public class BookEn {
	@Id
	@Column(name = "ID")
	@GeneratedValue(strategy = GenerationType.TABLE) // primary key autogenerated --hibernate
	private int bookId;
	private String bookName;
	private double bookPrice;
	@Column(name = "BOOK_REVIEWS")
	private String bookRemarks;
	
	public BookEn(int bookId, String bookName, double bookPrice, String bookRemarks) {
		super();
		this.bookId = bookId;
		this.bookName = bookName;
		this.bookPrice = bookPrice;
		this.bookRemarks = bookRemarks;
	}
	public BookEn() {
		super();
		// TODO Auto-generated constructor stub
	}
	@Override
	public String toString() {
		return "\n [bookId=" + bookId + ", bookName=" + bookName + ", bookPrice=" + bookPrice + ", bookRemarks="
				+ bookRemarks + "]";
	}
	public int getBookId() {
		return bookId;
	}
	public void setBookId(int bookId) {
		this.bookId = bookId;
	}
	public String getBookName() {
		return bookName;
	}
	public void setBookName(String bookName) {
		this.bookName = bookName;
	}
	public double getBookPrice() {
		return bookPrice;
	}
	public void setBookPrice(double bookPrice) {
		this.bookPrice = bookPrice;
	}
	public String getBookRemarks() {
		return bookRemarks;
	}
	public void setBookRemarks(String bookRemarks) {
		this.bookRemarks = bookRemarks;
	}
	
	
	
	
}
